AbcSize:
  Enabled: false
AlignParameters:
  Enabled: false
AndOr:
  Enabled: false
BlockLength:
  Enabled: false
CaseEquality:
  Enabled: false
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
DoubleNegation:
  Enabled: false
EachWithObject:
  Enabled: false
EndAlignment:
  EnforcedStyleAlignWith: "variable"
GuardClause:
  Enabled: false
IndentHash:
  Enabled: false
IndentHeredoc:
    Enabled: false
LineLength:
  Max: 100
MethodLength:
  Enabled: false
NestedMethodDefinition:
  Enabled: false
NonNilCheck:
  Enabled: false
ParameterLists:
  Max: 6
RegexpLiteral:
  Enabled: false
RescueException:
  Enabled: false
SignalException:
  Enabled: false
SpecialGlobalVars:
  Enabled: false
StringLiterals:
  EnforcedStyle: "double_quotes"
TrailingCommaInArguments:
  Enabled: false
TrailingCommaInLiteral:
  Enabled: false
TrivialAccessors:
  Enabled: false
