language: "ruby"
sudo: false
cache: "bundler"
rvm:
  - "2.5"
  - "jruby-9.1.16.0"
  - "rbx-3"
matrix:
  allow_failures:
    - rvm: "jruby-9.1.16.0"
    - rvm: "rbx-3"
  fast_finish: true
script: "bundle exec rake"
before_install:
  - "gem update --system"
  - "gem update bundler"
services:
  - "redis-server"
branches:
  except:
    - "/^v[0-9]/"
notifications:
  email: false
